5:38:7:dig2:Warn:DEBUG MODE ON. Can be slow !
5:38:7:alg:Info:analyze ./programs/hola/46.dig.c
5:38:7:alg:Info:set seed to: 1493807887.18 (test 28)
5:38:7:alg:Info:check reachability
5:38:7:alg:Info:gen eqts at 1 locs: l23 (int x, int z, int y, int w)
Traceback (most recent call last):
  File "dig2.py", line 71, in <module>
    doEqts=not args.noeqts, doIeqs=not args.noieqs)
  File "/home/tnguyen/Dropbox/git/dig2/alg.py", line 406, in start
    if doEqts: _gen('eqts')
  File "/home/tnguyen/Dropbox/git/dig2/alg.py", line 399, in _gen
    invs = solver.gen(deg, traces, inps)
  File "/home/tnguyen/Dropbox/git/dig2/alg.py", line 193, in gen
    initrs = [self.getInitTraces(loc, deg, traces, inps) for loc in traces]
  File "/home/tnguyen/Dropbox/git/dig2/alg.py", line 124, in getInitTraces
    assert newTraces[loc]
KeyError: 'l23'
